server:
  port: '8080'
hibernate:
  jdbc:
    use_streams_for_binary: 'false'
spring:
  jpa:
    database: postgresql
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    password: '123456'
    driver-class-name: org.postgresql.Driver
    username: suneclipse
    url: jdbc:postgresql://172.19.10.207:5433/velo_club
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        transaction: DEBUG
        orm:
          jpa: DEBUG
      hibernate:
        graph:
          internal: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: /test
jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: '36000000'
